### PR TITLE
use @aws-sdk/client-s3

### PR DESCRIPTION
**Pull request by gewisser**
Пытался заюзать деплой. Но yandex cloud возвращал content-type: **application/octet-stream**, для любого файла запрошенного с бакета. 

image

Подебажил и понял, что проблема с либой. Заменил на другую - поновей. Проблема ушла.

### CODE REVIEW

**Comment by PushoN** [comment]
С аналогичной проблемой столкнулся.

**Comment by sergeevpasha** [comment]
@PushoN @gewisser merged and fixed in v0.1.2

I hope this error comes from 0.1.1 version, otherwise these changes are pointless =D

**Comment by sergeevpasha** [comment]
@gewisser yeah... pointless update, feels like you tried v0.1.0 that has this bug and was fixed in 0.1.1
image

will revert it thou

**Comment by gewisser** [comment]
@sergeevpasha  I tried using version 0.1.1 and it should work as it should, but unfortunately it didn't. I had to fork the project and debug it. It was clear that despite the correctly specified content-type, a request was sent to the server without specifying the content-type. I didn't study the issue further. Just changed the dependency.

Now everything works as it should. Thank you!

**Pull request merged**
